### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by a113nGIT** [ccc-f/FCDN#2]
cmd@kali:~/FCDN-main$ python main.py -f domain.txt -t 100
Traceback (most recent call last):
  File "/home/cmd/FCDN-main/main.py", line 40, in <module>
    ThreadPool(cdn_check,urls,max_workers=thread_count)
  File "/home/cmd/FCDN-main/main.py", line 7, in ThreadPool
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 143, in __init__
    if max_workers <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'

执行子域名检测报错

**Comment by ccc-f** [comment]
现在可以了，感谢提醒，git pull 一下就好了。

**Comment by a113nGIT** [comment]
> 现在可以了，感谢提醒，git pull 一下就好了。

具体怎么git pull呢？

**Comment by a113nGIT** [comment]
cmd@kali:~/FCDN$ sudo python main.py -f domain.txt -t 20
[sudo] cmd 的密码：
Traceback (most recent call last):
  File "/home/cmd/FCDN/main.py", line 40, in <module>
    ThreadPool(cdn_check,urls,max_workers=thread_count)
  File "/home/cmd/FCDN/main.py", line 19, in ThreadPool
    savefile('./result/errorResult.txt',domain)
  File "/home/cmd/FCDN/main.py", line 22, in savefile
    with open(filename, 'a', encoding='utf-8')as f:
FileNotFoundError: [Errno 2] No such file or directory: './result/errorResult.txt'

最新的分支还是有问题。

**Comment by ccc-f** [comment]
ok
